### ISSUE TITLE
Github action for testing PRs

### ISSUE THREAD

**Issue by MarkusJohansen** [MarkusJohansen/ChimeraCSS#66]
**Is your feature request related to a problem? Please describe.**
We cant se wether our pipeline will fail until we actually attempt to release the code

**Describe the solution you'd like**
CI that attempts to compile and possible test the framework on pull request

**Comment by SindreKjelsrud** [comment]
@MarkusJohansen Isn't this issue completed?

**Comment by MarkusJohansen** [comment]
I guess it is outdated now as we currently test wether the code will compile on pull request. However we should unit test the code and run those tests in the workflow, but i think i should open another issue on this. Good catch @SindreKjelsrud!
